# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build node-interview`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t node-interview`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system node-interview && \
          adduser --system -G node-interview node-interview

COPY dist/node-interview node-interview/
RUN chown -R node-interview:node-interview .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix node-interview --omit=dev -f install

CMD [ "node", "node-interview" ]
